version: '2'
services:
  db:
    image: sashadock/postgres_database:latest
    hostname: db
  app:
    image: sashadock/rest_service_application:latest
    hostname: app
    ports:
      - 8080:8080
    links:
      - db:db 
    depends_on:
      - db